pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker run -v $PWD/Featherweight_OCL:/Featherweight_OCL logicalhacking:isabelle2019 isabelle build -D /Featherweight_OCL'
            }
        }
    }
}
