pipeline:
  build:
    image: docker.io/logicalhacking/isabelle2021-1
    commands:
      - export ARTIFACT_DIR=$CI_WORKSPACE/.artifacts/$CI_REPO/$CI_BRANCH/$CI_BUILD_NUMBER/
      - mkdir -p $ARTIFACT_DIR
      - isabelle build -D Featherweight_OCL -o browser_info  -o document=pdf
      - export `isabelle getenv ISABELLE_HOME_USER`
      - cp -r $ISABELLE_HOME_USER/browser_info $ARTIFACT_DIR
      - cd $ARTIFACT_DIR
      - cd ..
      - ln -s * latest
  deploy:
    image: docker.io/drillster/drone-rsync
    settings:
      hosts: [ "ci.logicalhacking.com"]
      port: 22
      source: .artifacts/$CI_REPO_OWNER/*
      target: $CI_REPO_OWNER
      include: [ "**.*"]
      key: 
        from_secret: artifacts_ssh
      user: artifacts
